### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ForestedDev** [tlrobinson/life-gen#1]
How would I install this, I have never used ruby before, also need to know where to run the code, preferably on phone, that is where I have golly.

**Comment by ForestedDev** [comment]
please help me

**Comment by tlrobinson** [comment]
Sorry, I haven’t worked on this in years, I don’t know if it still works.

**Comment by 0x2b3bfa0** [comment]
> [!NOTE]
> See https://tlrobinson.net/blog/2009/02/game-of-life-generator for usage instructions.
